[ADD] Tabelas eSocial 01, 02, 03, 13, 14, 15, 16, 17, 18 , 19, 20 , 2…
kmee/l10n-brazil pull request #275
Opened 2017-10-16 13:47 UTC by wagnerpereirasp

…1, 25 e 26

2017-10-19 18:40 UTC, mileo requested changes
Favor corrigir o readme do módulos com o nome da KMEE e o nome correto dos autores em todos os arquivos

2017-10-19 18:40 UTC, mileo commented on esocial/README.rst
> +* Luis Felipe Mileo <mileo@kmee.com.br>
Favor remover meu nome, pois eu não ajudei

2017-10-19 18:40 UTC, mileo commented on esocial/__init__.py
> +# Copyright 2017 KMEE - Luis Felipe Miléo <mileo@kmee.com.br>
Novamente

2017-10-23 13:46 UTC, wagnerpereirasp commented on esocial/README.rst
> +* Luis Felipe Mileo <mileo@kmee.com.br>
Corrigido

2017-10-23 13:46 UTC, wagnerpereirasp commented on esocial/__init__.py
> +# Copyright 2017 KMEE - Luis Felipe Miléo <mileo@kmee.com.br>
Corrigido

2017-10-23 13:46 UTC, merged