[WIP] 10.0 feature/fluxo compras
kmee/l10n-brazil pull request #376
Opened 2017-12-04 19:36 UTC by HugoUchoasBorges

Sped_purchase portado para Odoo10
- Cálculos do pedido de compra funcionando

2018-01-29 20:19 UTC, hendrixcosta commented on sped_nfe/models/inherited_sped_documento.py
> +
expected singleton()

2018-01-29 20:19 UTC, Hendrixcosta commented on sped_purchase/models/inherited_purchase_order.py
> -        self.write({'state': 'purchase'})
Expected singleton()

2018-01-29 20:19 UTC, Hendrixcosta commented on sped_purchase/models/inherited_purchase_order.py
> +    kanban_state = fields.Selection(
Se o campo eh computado, acho que tem que definir uma atribute inverse para não ficar readonly

2018-01-29 20:23 UTC, hendrixcosta requested changes
Na tela de nova cotação, dominio tem que ser:
'eh_fornecedo' = True
![image](https://user-images.githubusercontent.com/7250580/35532453-6b73949a-0521-11e8-8dbf-840d590db96c.png)

2018-01-29 20:24 UTC, hendrixcosta requested changes
Acho melhor traduzir "New" para "nova"
campo is_brazilian tem que ser invisible
![image](https://user-images.githubusercontent.com/7250580/35532504-99e460b6-0521-11e8-8caa-ca2c5ec1f9bc.png)

2018-01-29 20:30 UTC, hendrixcosta requested changes
Quando seleciono um item, deveria vir o preço de custo, não?
(veio o preço de venda
![image](https://user-images.githubusercontent.com/7250580/35532716-5705aa74-0522-11e8-889a-a296c41f77cf.png)

2018-01-29 21:07 UTC, hendrixcosta requested changes
Configurar o _rec_name
![image](https://user-images.githubusercontent.com/7250580/35534411-984ba3da-0527-11e8-939d-69f59d9975d9.png)

2018-01-31 11:49 UTC, HugoUchoasBorges commented on sped_purchase/models/inherited_purchase_order.py
> +    kanban_state = fields.Selection(
Nesse caso, pela funcionalidade, o kanban_state deve ficar como readonly mesmo.

2018-01-31 12:46 UTC, closed without merging