10.0 feature/boleto nfe francesinha
kmee/l10n-brazil pull request #384
Opened 2017-12-09 08:14 UTC by Hendrixcosta

2017-12-13 10:35 UTC, mileo requested changes

2017-12-13 10:35 UTC, mileo commented on finan/__manifest__.py
> +        'sped_sale',
Esta dependência não é permtida

2017-12-13 10:35 UTC, mileo commented on finan/__manifest__.py
> +        'sped_sale',
Creio que parte de emissão de boleto junto com a venda deve estar em outro módulo, não no finan.

2017-12-13 10:47 UTC, Hendrixcosta commented on finan/__manifest__.py
> +        'sped_sale',
Essa herança é por causa da herança da view que acrescenta informações da carteira na venda
https://github.com/kmee/l10n-brazil/pull/384/files#diff-06d4f66c51ace05fcbcb6b707aca6021R11

2017-12-13 17:06 UTC, hendrixcosta commented
:+1: @mileo

2017-12-14 19:25 UTC, mileo approved these changes

2017-12-14 19:25 UTC, merged