[FIX] fechamento de caixa
kmee/l10n-brazil pull request #402
Opened 2017-12-19 12:40 UTC by the-bmb

Correção no calculo do saldo para que leve em consideração se o lançamento é pagamento ou recebimento.

2017-12-19 13:49 UTC, BiancaBartolomei commented
@the-bmb 
O for com elif ta fazendo com que nao calcule corretamente, só trocar por if que dá certo. 
O campo "saldo dos lançamentos", se um fechamento de caixa já foi feito, e vai ser processado outro ele soma com o saldo anterior, acho que nesse caso deveria ser só o saldo dos lançamentos em si, desconsiderando o anterior.

2017-12-20 19:18 UTC, hendrixcosta commented
@the-bmb  por favor usar o padrão na nomenclatura da branch.
[versao]-[funcao] / [nome da branch]
10.0-fix/fechamento_caixa

2017-12-20 19:29 UTC, hendrixcosta requested changes

2017-12-20 19:29 UTC, Hendrixcosta commented on finan/models/finan_banco_fechamento.py
>      @api.depends('lancamento_ids')
Inserir linha em branco

2017-12-20 19:29 UTC, Hendrixcosta commented on finan/views/finan_banco_fechamento.xml
> +                                    <field name="vr_documento"/>
No cálculo do saldo é utilizado o campo vr_total e aqui é exibido o campo vr_documento.
Aqui deveria ser o campo vr_total.

2017-12-20 19:29 UTC, Hendrixcosta commented on finan/views/finan_banco_fechamento.xml
> +                              </group>
Identação

2017-12-20 21:45 UTC, hendrixcosta requested changes

2017-12-20 21:45 UTC, Hendrixcosta commented on finan/models/finan_banco_fechamento.py
>      @api.depends('lancamento_ids')
Usar tambem a @api.multi

2017-12-22 15:45 UTC, closed without merging