[FIX]Visibilidade de botões dependendo do usuario
kmee/l10n-brazil pull request #425
Opened 2018-01-02 20:08 UTC by BiancaBartolomei

Adicionar permissão ao Botão de processamento do retorno do CNAB.
Adicionar permissão ao Botão de processamento da remessa do CNAB.
Apenas operadores do financeiro podem ver os botões.

https://docs.google.com/a/kmee.com.br/document/d/101721bCpypstZqIwgFA7RtpjtyDRU6SdBaWzCe3CRwU/edit?usp=sharing

2018-01-03 12:08 UTC, hendrixcosta approved these changes

2018-01-04 14:43 UTC, isamaia approved these changes

2018-01-05 02:38 UTC, hendrixcosta requested changes

2018-01-05 02:38 UTC, Hendrixcosta commented on finan/views/finan_remessa_boleto_view.xml
> +                    <button name="gera_arquivo" string="Gera arquivo" class="btn-primary" type="object" groups="finan.GRUPO_CADASTRO_GERAL, finan.GRUPO_CADASTRO_GERENTE"/>
Depois de implementado herança das permissões utilizar apenas a permissão de mais baixo nível.

2018-01-08 13:02 UTC, hendrixcosta approved these changes

2018-01-08 13:04 UTC, merged