[WIP]Cancelamento de NFe
kmee/l10n-brazil pull request #494
Opened 2018-01-23 17:21 UTC by BiancaBartolomei

Atividade referente a  Fiscal - Fluxo do Cancelamento da NFe

2018-01-23 17:52 UTC, mileo requested changes

2018-01-23 17:52 UTC, mileo commented on sped_nfe/wizards/wizard_nfe_motivo_cancelamento.py
> +class FinanLancamento(models.TransientModel):
???????????

2018-01-24 14:21 UTC, hendrixcosta approved these changes

2018-01-24 16:54 UTC, BiancaBartolomei commented
Funciona corretamente

2018-01-25 17:33 UTC, mileo commented on sped_nfe/wizards/wizard_nfe_motivo_cancelamento.py
> +            raise UserError("A justificativa deve ter mais de 10 caracteres.")
Se eu não me engano o cancelamento tb tem um tamanho máximo. Seria interessante colocar este limite no campo limit do text/char.

2018-01-26 19:37 UTC, Hendrixcosta commented on sped_nfe/wizards/wizard_nfe_motivo_cancelamento.py
> +            raise UserError("A justificativa deve ter mais de 10 caracteres.")
@BiancaBartolomei

2018-01-26 20:54 UTC, Hendrixcosta commented
Cancelou a nota corretamente.
![image](https://user-images.githubusercontent.com/7250580/35460199-4bee37f0-02ca-11e8-936d-491b547971ec.png)

2018-01-26 20:54 UTC, hendrixcosta approved these changes

2018-01-26 21:13 UTC, mileo approved these changes

2018-01-26 21:13 UTC, merged