10.0 feature/fluxo compras usabilidade
kmee/l10n-brazil pull request #497
Opened 2018-01-24 19:27 UTC by HugoUchoasBorges

Neste PR estão os commits do PR #376 que afetam apenas a usabilidade do Manifesto do Destinatário e Importação de NF-e

Changelog
- Na Manifestação, foi separado o botão "Download NF-e" em  Importar\Download da NF-e. O primeiro cria um sped_documento com a NF-e importada, o outro apenas salva seu XML 
- Campo ultima_consulta da 'Busca DF-e' agora funciona
- Botão para Importadar todas as NF-e a partir do 'Busca DF-e'
- Botões para Download do XML e Importação da NF-e  na TREE da manifestação do destinatário
- Opção para utilização de CRON no 'Busca DF-e'
- Agora ao dar um erro na importação de uma NF-e é mostrado código+mensagem de erro da Receita Federal

- Na TREE 'Manifestação do Destinatário" agora é possível gerenciar múltiplas manifestações através do CheckBox, no menu Action-->Gerenciar Selecionados
  -  Dentro desse Wizard é possível salvar múltiplos XMLs compactados em 1 arquivo

OBS:  Alguns pequenos ajustes para o Fluxo de Compras estão listados aqui, mas a funcionalidade em si apenas está no PR #376

2018-01-30 21:08 UTC, hendrixcosta requested changes

2018-01-30 21:08 UTC, hendrixcosta commented on sped/models/sped_documento.py
> +        # result.executa_depois_create()
Não sei se o ideal eh remover o processamento desse gancho... 
Pode ser que em outros módulos ele esta sendo utilizado

2018-01-30 21:08 UTC, hendrixcosta commented on sped_nfe/models/inherited_sped_documento.py
> +            'res_id': self.id,
Entra no expected singleton que a gente conversou mais cedo.
Se tem certeza que vem apenas um item acrescentar self.ensure_one

2018-01-30 21:08 UTC, hendrixcosta commented on sped_nfe/models/sped_consulta_dfe.py
> +    cron = fields.Boolean(
Acho que o nome da variável não ficou muito intuitivo.

2018-01-30 21:08 UTC, hendrixcosta commented on sped_nfe/models/sped_consulta_dfe.py
> +            'limit':len(self.env['sped.manifestacao.destinatario'].search([(
Temos o search_count que ja traz do banco apenas a quantidadde de registros encontrados.

2018-01-30 21:08 UTC, hendrixcosta commented on sped_nfe/models/sped_consulta_dfe.py
> +    def action_gerencia_manifestacoes(self):
Você não poderia substituir esse método por uma action em xml?

2018-01-30 21:08 UTC, Hendrixcosta commented on sped_nfe/models/sped_consulta_dfe.py
> +
Faltou uma explicação do método e no final pulou 2 linhas. PEP8 Não passara!

2018-01-30 21:08 UTC, Hendrixcosta commented on sped_nfe/models/sped_consulta_dfe.py
>                  last_nsu = self.ultimo_nsu
Nao deveria ser `consulta.ultimo_nsu` ?

2018-01-30 21:08 UTC, Hendrixcosta commented on sped_nfe/models/sped_consulta_dfe.py
> +                self.ultima_consulta = fields.Datetime.now()
`consulta.ultima_consulta` ?

2018-01-30 21:08 UTC, Hendrixcosta commented on sped_nfe/models/sped_consulta_dfe.py
>                               company, last_nsu)
`company.name`

2018-01-30 21:10 UTC, Hendrixcosta commented on sped_purchase/models/inherited_purchase_order.py
> +        self.ensure_one()
:+1:

2018-01-30 21:14 UTC, hendrixcosta submitted a review, later dismissed

2018-01-30 21:14 UTC, Hendrixcosta commented on sped_purchase/models/sped_documento.py
> +        for documento in self:
Se for pra alterar o comportamento depois de chamar o super, acho que deveria iterar o res e não o self.

2018-01-30 21:14 UTC, Hendrixcosta commented on sped_purchase/wizard/sped_consulta_status_documento.py
> +        attachment=True
Vírgula no final pra não perder o costume

2018-01-30 21:55 UTC, mileo requested changes

2018-01-30 21:55 UTC, mileo commented on sped_nfe/models/sped_manifestacao_destinatario.py
> +        return {
É possível baixar mais de um documento ? Se sim o usuário deve ser redirecionado para uma view do tipo tree com vários registros

2018-01-30 21:55 UTC, mileo commented on sped_nfe/models/sped_manifestacao_destinatario.py
> +        self[0].sped_consulta_dfe_id.baixa_documentos(manifestos=self)
self.ensure_one()
self.sped_consulta_dfe_id.baixa_documentos(manifestos=self)

2018-01-31 04:04 UTC, Hendrixcosta commented on sped_purchase/models/sped_documento.py
> +        purchase_order_ids = self.mapped('purchase_order_ids')
Nao deveria utilizar o res?
` purchase_order_ids = res.mapped('purchase_order_ids')`

2018-01-31 04:05 UTC, Hendrixcosta commented on sped_purchase/models/stock_picking.py
> +        for separacao in self:
Mesmo esquema de utilização do "res", ao inves do self

2018-01-31 04:05 UTC, Hendrixcosta commented on sped_purchase/models/stock_picking.py
> +        for separacao in self:
?

2018-01-31 04:07 UTC, Hendrixcosta commented on sped_purchase/wizard/sped_consulta_status_documento.py
> +                'context': {'default_purchase_order_ids': [
expected singleton()

2018-01-31 04:26 UTC, mileo commented on sped_purchase/models/sped_documento.py
> +        purchase_order_ids = self.mapped('purchase_order_ids')
newba

2018-01-31 10:52 UTC, mileo approved these changes

2018-01-31 10:52 UTC, merged