[FIX]Mover de data para dados de demonstração
kmee/l10n-brazil pull request #501
Opened 2018-01-26 12:16 UTC by BiancaBartolomei

PR referente a atividade [BAIXA] SPED - DEMO

2018-01-30 18:42 UTC, hendrixcosta submitted a review, later dismissed

2018-01-30 18:42 UTC, Hendrixcosta commented on sped/__manifest__.py
> +        'demo/sped_participante_demo.xml',
Para mover para dados de demonstração é precisa adicionar na chave certa do dict.
Observe o manifest do finan para visualizar a diferença:
https://github.com/kmee/l10n-brazil/blob/10.0-develop/finan/__manifest__.py

2018-01-30 18:50 UTC, Hendrixcosta commented on sped/__manifest__.py
> +        'demo/sped_participante_demo.xml',
@isamaia

2018-01-30 22:03 UTC, mileo approved these changes

2018-01-31 01:28 UTC, hendrixcosta requested changes

2018-01-31 01:28 UTC, Hendrixcosta commented on sped/__manifest__.py
>          'data/sped_participante_data.xml',
Essa linha não deveria existir já que foi portada para demonstração

2018-01-31 01:55 UTC, hendrixcosta approved these changes

2018-01-31 01:56 UTC, merged