[FIX] Adicionando cláusula para seguir também no fluxo de venda
kmee/l10n-brazil pull request #505
Opened 2018-01-26 20:29 UTC by Hendrixcosta

O fluxo de venda esta quebrado.
Foi adicionado uma clausula para ser possível emitir nfe apartir da sale.order

2018-01-26 20:31 UTC, mileo requested changes
self._name not 'sped.documento':

2018-01-26 20:32 UTC, mileo requested changes

2018-01-26 20:32 UTC, mileo commented on sped_imposto/models/sped_calculo_imposto.py
> +            # if self.pagamento_ids:
Qual o motivo da remoção?

2018-01-26 20:32 UTC, mileo commented on sped_imposto/models/sped_calculo_imposto.py
> +        if isinstance(self.id, models.NewId) or self._name == 'sale.order':
or self._name not 'sped.documento':

2018-01-26 20:36 UTC, Hendrixcosta commented on sped_imposto/models/sped_calculo_imposto.py
> +            # if self.pagamento_ids:
A sale.order nao tem pagamento_ids e uma linha acima temos:
documento = self

2018-01-26 21:37 UTC, mileo requested changes

2018-01-26 21:37 UTC, mileo commented on sped_imposto/models/sped_calculo_imposto.py
> +            # if self.pagamento_ids:
Faz então um if hasattr(documento,'pagamento_ids'):

2018-01-26 22:20 UTC, mileo requested changes

2018-01-26 22:20 UTC, mileo commented on sped_imposto/models/sped_calculo_imposto.py
> +        if hasattr(self, 'pagamento_ids'):
Deveria ser documento não self

2018-01-27 00:10 UTC, Hendrixcosta commented on sped_imposto/models/sped_calculo_imposto.py
> +        if hasattr(self, 'pagamento_ids'):
"documento" pelo que eu entendi, seria o documento gerado apartir do self.
Se eu gerei um objeto a partir do outro, devo portar as informações do antigo para o novo.

Se eu testar no documento e não no self , nao faz sentido pra mim a linha 663:
``` documento.pagamento_ids = self.pagamento_ids ```

2018-01-27 18:26 UTC, mileo commented on sped_imposto/models/sped_calculo_imposto.py
> +        if hasattr(self, 'pagamento_ids'):
Então esta refletindo sobre isso, acho que esta linha não deveria nem existir. Pois realmente elas não fazem sentido, mas ontem estava fazendo mil coisas ao mesmo tempo e ai não deu pra parar e analisar direito

2018-01-28 23:07 UTC, mileo approved these changes

2018-01-28 23:07 UTC, merged