Importação de NF-e cancelada
kmee/l10n-brazil pull request #521
Opened 2018-02-05 01:47 UTC by HugoUchoasBorges

O que funciona:
- Importação apenas do XML do cancelamento da NF-e (tendo o documento já importado) pelo wizard 'Consultar Documento'
- Importação de uma pasta contendo diversos arquivos, entre eles o XML de cancelamento (submenu Importa NF-e)

O campo 'data_hora_cancelamento' ficou como pendente, faltando fazer sua conversão de String no formato ISO para fields.Datetime

2018-02-05 13:42 UTC, mileo requested changes

2018-02-05 13:42 UTC, mileo commented on sped_nfe/models/sped_importa_nfe.py
> +            self.protocolo_cancelamento = nfe.retEvento.infEvento.nProt
Creio que isto esteja incorreto

2018-02-05 13:44 UTC, mileo commented
`            
data_cancelamento = retevento.infEvento.dhRegEvento.valor
data_cancelamento = UTC.normalize(data_cancelamento)
self.data_hora_cancelamento = data_cancelamento
`

2018-02-05 15:05 UTC, mileo commented on sped_nfe/models/sped_importa_nfe.py
> +            nome_arquivo = chave + '-01-proc-can.xml'
Nem sempre o número do evento vai ser o 01

2018-02-05 15:12 UTC, mileo requested changes

2018-02-05 15:12 UTC, mileo commented on sped_nfe/models/sped_importa_nfe.py
> +                if 'proc-can' in filename:
Nem todo xml pode ter o nome correto. 

O ideal é que vc tente processar o arquivo, então ao meu ver esta lógica toda deveria estar dento do le_nfe.

2018-02-05 19:06 UTC, mileo commented on sped_nfe/models/le_nfe/inherited_sped_documento.py
> +        if getattr(nfe, 'evento', None):
Este código não deveria mais a baixo, depois da confirmação do modelo do documento?

2018-02-05 19:06 UTC, mileo commented on sped_nfe/models/sped_importa_nfe.py
> +                    print u"Exception:  " + filename
Pode colocar um log.error ao invés de um print?

2018-02-05 19:07 UTC, mileo commented on sped_nfe/models/sped_importa_nfe.py
> +        arquivos_cancelamento = []
Não seria melhor chamarmos de arquivos_eventos ? Pois podemos ter mais eventos alem do cancelamento

2018-02-06 00:07 UTC, HugoUchoasBorges commented on sped_nfe/models/le_nfe/inherited_sped_documento.py
> +        if getattr(nfe, 'evento', None):
Acontece que se o documento for um XML de cancelamento, ele não carrega a informação do modelo do documento.

Ou seja, se o código for pra baixo da confirmação do modelo, o método sempre retornará antes de chegar no código, falando que o Modelo não é suportado antes mesmo de verificar que é um XML de cancelamento

2018-02-06 10:15 UTC, mileo approved these changes

2018-02-06 10:15 UTC, merged