[FIX] Erro unicode - fluxo de caixa
kmee/l10n-brazil pull request #523
Opened 2018-02-05 17:06 UTC by isamaia

2018-02-05 19:47 UTC, hendrixcosta requested changes

2018-02-05 19:47 UTC, Hendrixcosta commented on finan/reports/finan_relatorio_fluxo_caixa.py
> +                if data_atual.month == 03:
Acho que nao precisava desse if, podendo ser convertido em utf-8 pra todos os meses.
1 linha de código você resolve

2018-02-06 10:28 UTC, gabrielcardoso21 approved these changes

2018-02-06 12:33 UTC, hendrixcosta approved these changes

2018-02-06 12:33 UTC, merged