Emissão de CF-E via py3o
kmee/l10n-brazil pull request #535
Opened 2018-02-18 20:55 UTC by mileo

2018-02-19 19:29 UTC, sadamo approved these changes

2018-02-19 21:09 UTC, gabrielcardoso21 requested changes

2018-02-19 21:09 UTC, gabrielcardoso21 commented on sped_nfe/models/monta_nfe/inherited_sped_documento.py
> +        nfe.infNFe.infAdic.infAdFisco.valor = self._monta_informacao_fisco()
Função não existe. Deve-se remover o _nfe da declaração da função na linha 550 ou adicionar _nfe no nome chamado nessa linha.

2018-02-21 12:21 UTC, gabrielcardoso21 requested changes

2018-02-21 12:21 UTC, gabrielcardoso21 commented on sped_nfe/models/monta_nfe/inherited_sped_documento_item.py
> +        det.infAdProd.valor = self._monta_nfe_informacoes_adicionais()
Essa função precisa do argumento nfe e não tem retorna nada

2018-02-27 05:31 UTC, closed without merging