Feature/cadastro cliente pos pr
kmee/l10n-brazil pull request #539
Opened 2018-02-19 18:38 UTC by atillaSilva

2018-02-20 08:22 UTC, gabrielcardoso21 requested changes

2018-02-20 08:22 UTC, gabrielcardoso21 commented on l10n_br_pos/static/src/xml/pos.xml.orig
> +<<<<<<< HEAD
Tem um conflito de git não resolvido aqui.

2018-02-20 13:15 UTC, atillaSilva commented
alteração feita @gabrielcardoso21

2018-02-28 19:58 UTC, lfdivino requested changes

2018-02-28 19:58 UTC, lfdivino commented on l10n_br_pos/models/res_partner.py
> +    def get_states_ids(self, id_country):
Esta função está no modelo errado não?

2018-02-28 19:58 UTC, lfdivino commented on l10n_br_pos/models/res_partner.py
> +    def get_city_ids(self, id_state):
Esta função está no modelo errado não?

2018-02-28 19:58 UTC, lfdivino commented on l10n_br_pos/models/res_partner.py
> +        partner['data_alteracao'] = fields.Date.today()
Somente um campo de data de alteração é o suficiente, é identificado qual(is) campo(s) foi alterado(s) nesta última alteração?

2018-02-28 19:58 UTC, lfdivino commented on l10n_br_pos/static/src/js/screens.js
> +                    var ss = self.pos.pos_widget.screen_selector;
Após essa linha setar o cliente criado no objeto da Order

2018-03-02 17:57 UTC, BiancaBartolomei requested changes
Para a atividade "Criar um onchange no combobox do estado para que ao selecionar...", quando coloca um estado ou país, e depois seleciona de novo e volta para "nenhum" ele dá o erro DataError: invalid input syntax for integer: ""
LINHA 1: ...res_country_state" WHERE "res_country_state".id = '' ORDER B...
Já as outras atividades (campo date, campo cliente desde e voltar para tela principal do ponto de venda), estão funcionando corretamente da maneira especificada

2018-03-06 13:28 UTC, merged