[FIX] auto complete de estado e país
kmee/l10n-brazil pull request #583
Opened 2018-04-10 17:17 UTC by the-bmb

Descrição do problema/nova funcionalidade deste Pull Resquest(PR):
------------------------------------------------------------------

-
-
-

Comportamento atual antes do PR:
--------------------------------

Comportamento esperado depois do PR:
------------------------------------

- [ ] Esta mudança não altera a estrutura do banco de dados, portanto não precisa de script de migração.

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2018-04-10 17:22 UTC, mileo approved these changes

2018-04-10 17:22 UTC, mileo requested changes
O estado tb esta invisível?

2018-04-10 17:32 UTC, the-bmb commented
Sim, está. A sigla do estado aparece ao lado do nome da cidade.

2018-04-10 17:36 UTC, mileo commented
Sim, mas o campo res.country.state esta sendo exibido?

2018-04-11 02:55 UTC, mileo commented
Cherry-pick realizado

2018-04-11 02:55 UTC, closed without merging