[ADD]Campo de desconto impressao cfe
kmee/l10n-brazil pull request #589
Opened 2018-04-26 18:33 UTC by sadson

Descrição do problema/nova funcionalidade deste Pull Resquest(PR):
------------------------------------------------------------------

-
-
-

Comportamento atual antes do PR:
--------------------------------

Comportamento esperado depois do PR:
------------------------------------

- [ ] Esta mudança não altera a estrutura do banco de dados, portanto não precisa de script de migração.

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2018-04-26 21:55 UTC, mileo commented
@gabrielcardoso21 pode revisar por favor

2018-04-27 14:23 UTC, gabrielcardoso21 requested changes
A parte da informação complementar dos itens foi retirada. Favor colocar novamente.

2018-08-07 04:53 UTC, mileo commented
@sadson alguma resposta?

2018-08-08 20:49 UTC, mileo commented
Devido a falta de resposta estou fechando este PR

2018-08-08 20:49 UTC, closed without merging