[IMP] payment_pagseguro: Query the status of the pix through the webhook.
kmee/l10n-brazil pull request #701
Opened 2022-06-20 20:10 UTC by cristiano-one

@sadamo Lembrando que precisamos fazer testes desta funcionalidade em produção.

2022-06-21 15:11 UTC, sadamo requested changes

2022-06-21 15:11 UTC, sadamo commented on payment_pagseguro/controllers/main.py
> +        transaction_id = (
Neste caso, o search está buscando qualquer pagamento? Na notificação não vem nenhuma informação sobre qual é a transação que ela está notificando? 
Caso a notificação enviada pela pagseguro não informe qual é o pagamento, uma sugestão seria buscar todas as transactions que são feitas por pix e estão com status pendente de pagamento e chamar o método pagseguro_search_payment_pix para elas.

2022-06-21 15:11 UTC, sadamo commented on payment_pagseguro/models/payment_transaction.py
> +        notification_code = params["notificationCode"]
Esse método não precisa ser com @api.multi, pois não está trabalhando com um record em si. Recomendo ser @api.model e na rota de notificação utilizar somente o request.env['payment.transaction'].sudo() (sem o search), para chamar o pagseguro_search_payment_pix.

2022-06-22 15:00 UTC, cristiano-one commented on payment_pagseguro/controllers/main.py
> +        transaction_id = (
Verdade, já fiz as alterações. No caso não precisou eu fazer nenhuma verificação neste ponto , pois eu já faço isso dentro do método pagseguro_search_payment_pix().

2022-06-22 15:00 UTC, cristiano-one commented on payment_pagseguro/models/payment_transaction.py
> +        notification_code = params["notificationCode"]
Feito

2022-06-24 18:13 UTC, sadamo requested changes

2022-06-24 18:13 UTC, sadamo commented on payment_pagseguro/models/payment_transaction.py
> +        _logger.error("Failed to receive Webhook notification.")
Acredito que _logger.error() poderia estar num else, pois da forma atual ele está logando que deu erro mesmo tendo funcionado corretamente.

2022-06-28 10:13 UTC, sadamo approved these changes

2022-06-28 10:13 UTC, merged